services:
  - type: web
    name: sunflower-data-collective
    env: python
    plan: free
    buildCommand: pip install -r site/requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT site.app:app
    envVars:
      - key: DEMO_URL
        value: https://sunflower-data-collective.streamlit.app/
